### PR TITLE
Updating the auto-generated WMI wrapper files based on the latest run of wmigen

### PR DESCRIPTION
**Pull request by JocelynBerrendonner**
Updating the auto-generated WMI files based on the latest run of wmigen. I ran wmigen.exe using the wmigen onebranch pipeline (https://dev.azure.com/msazure/msk8s/_build/results?buildId=95384487&view=artifacts&pathAsName=false&type=publishedArtifacts) and manually copied the generated GO wrapper files back to github.com/microsoft/wmi. This is the resulting PR for the above change.

### CODE REVIEW

**Comment by madhanrm** [comment]
Should we put the new files in server2022 or server23h2 ?

**Comment by JocelynBerrendonner** [comment]
> Should we put the new files in server2022 or server23h2 ?

Done

**Review by madhanrm — APPROVED** [review]

**Review by raghavendra-nataraj — APPROVED** [review]

**Review by raghavendra-nataraj — APPROVED** [review]

**Pull request merged**
